#!/bin/bash
TESTS=$(ls tests)

echo "" > input.txt
for i in {1..200}
do
    echo "$((1 + $RANDOM % 100))" >> input.txt
done

for tst in $TESTS
do
    RKT="(match $(cat tests/$tst) [(? boolean? b) (if b 1 0)] [other other])"
    racket -e "$RKT" > rkt_out.txt < input.txt

    scripts/blungentle tests/$tst temp
    ./temp < input.txt > my_out.txt

    Diff=$(diff rkt_out.txt my_out.txt)
    if [[ "$Diff" != "" ]]; then
        printf "Test %-20s \033[0;31mFailed\033[0m" "$tst":
        echo
        >&2 printf "\033[1;33m------------------------------------------\033[0m\n"
        >&2 printf "\033[1;33m%s\033[0m\n" "$Diff"
        >&2 printf "\033[1;33m------------------------------------------\033[0m\n"
        Exit=1
    else
        printf "Test %-20s \033[0;32mPassed\033[0m" "$tst":
        echo
    fi
done